{
  "name": "F 05 16",
  "compatibilityLevel": 1550,
  "model": {
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "sourceQueryCulture": "it-IT",
    "tables": [
      {
        "name": "Customer",
        "lineageTag": "6ee73db7-6ef7-472f-8766-503e56c49f8c",
        "columns": [
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "CustomerKey",
            "lineageTag": "1972b4cf-eab2-42e1-a914-e03a04ec689f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Customer Code",
            "dataType": "string",
            "sourceColumn": "Customer Code",
            "lineageTag": "0ace8b5f-6e2a-4898-a85b-ee8a24c1f31a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Title",
            "dataType": "string",
            "sourceColumn": "Title",
            "lineageTag": "08d2c273-cb90-43b6-b779-362c2132d8f8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Name",
            "dataType": "string",
            "sourceColumn": "Name",
            "lineageTag": "36c04453-2e71-4ef8-9a5f-7aff98e93293",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Birth Date",
            "dataType": "dateTime",
            "sourceColumn": "Birth Date",
            "formatString": "Long Date",
            "lineageTag": "417f0948-127e-438d-a5b6-82f8773c2d20",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Marital Status",
            "dataType": "string",
            "sourceColumn": "Marital Status",
            "lineageTag": "9da911d6-71bb-4aab-b931-c51a90a0d32d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Gender",
            "dataType": "string",
            "sourceColumn": "Gender",
            "lineageTag": "6c9bd22a-cd53-4726-9d9b-a4581d2613f8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Yearly Income",
            "dataType": "decimal",
            "sourceColumn": "Yearly Income",
            "lineageTag": "6ff7bd75-7979-4d9a-858f-b01da1299e26",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Total Children",
            "dataType": "int64",
            "sourceColumn": "Total Children",
            "lineageTag": "5e36829d-2942-4670-85ac-3eefaf141ddd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Children At Home",
            "dataType": "int64",
            "sourceColumn": "Children At Home",
            "lineageTag": "906605e1-925a-4739-9644-c71b3795d01f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Education",
            "dataType": "string",
            "sourceColumn": "Education",
            "lineageTag": "65f1fd98-46fb-4511-8618-4f7cd10ec043",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Occupation",
            "dataType": "string",
            "sourceColumn": "Occupation",
            "lineageTag": "48481720-fbc1-4956-8dcd-54ff6cb2fdd6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "House Ownership",
            "dataType": "string",
            "sourceColumn": "House Ownership",
            "lineageTag": "090581a2-58d3-4462-b4ec-ee9ae37adad9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Cars Owned",
            "dataType": "int64",
            "sourceColumn": "Cars Owned",
            "lineageTag": "fd4ba58e-da9d-4d43-a878-4a3f43659647",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent",
            "lineageTag": "08648c79-62bc-47d2-b223-5148b36a2740",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "5c1c9cbf-f7cd-40e4-b4dd-0187df4e69b3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "b952855b-be08-48fe-9523-fce58a435875",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Address Line 1",
            "dataType": "string",
            "sourceColumn": "Address Line 1",
            "lineageTag": "45ea4a4a-1b79-4e15-bca2-499b677b3303",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Address Line 2",
            "dataType": "string",
            "sourceColumn": "Address Line 2",
            "lineageTag": "d88eb2cd-171b-4ab3-b66f-abe1aa0fa2d6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Phone",
            "dataType": "string",
            "sourceColumn": "Phone",
            "lineageTag": "b094606f-8c95-4fd6-965e-1a58218f5209",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Date First Purchase",
            "dataType": "dateTime",
            "sourceColumn": "Date First Purchase",
            "formatString": "Long Date",
            "lineageTag": "a4ac6312-7830-4310-9f98-a1a478e0ea50",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Customer Type",
            "dataType": "string",
            "sourceColumn": "Customer Type",
            "lineageTag": "5b7efd42-eace-405e-8c72-2643ff585319",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Company Name",
            "dataType": "string",
            "sourceColumn": "Company Name",
            "lineageTag": "f2fcc456-28ee-420c-aafe-bf6b5dd37beb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "CountryRegion",
            "dataType": "string",
            "sourceColumn": "CountryRegion",
            "lineageTag": "ec5d0f5b-477f-40d2-acd7-3dc2c226262c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DaxBook Customer",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\"),",
                "    DaxBook_Customer = Source{[Schema=\"DaxBook\",Item=\"Customer\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(DaxBook_Customer,{\"GeographyKey\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            },
            "annotations": [
              {
                "name": "IsQueryEditorUsed",
                "value": "False"
              },
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT * FROM [Customer]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "63"
          },
          {
            "name": "IsQueryEditorUsed",
            "value": "False"
          },
          {
            "name": "QueryEditorSerialization"
          },
          {
            "name": "TableWidgetSerialization"
          },
          {
            "name": "DataMarketWebBaseUrl"
          },
          {
            "name": "DataMarketWebQueryUrl"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "f8eca18d-c003-45a1-8672-8f2d636f2ebe",
        "columns": [
          {
            "name": "Date",
            "dataType": "dateTime",
            "isNullable": false,
            "sourceColumn": "Date",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "dadea7ed-d5f5-45e0-9000-4b8a5d6dbfd3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "DateKey",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "DateKey",
            "lineageTag": "94c579cc-5bb9-45ba-9037-50f0ffe313c0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calendar Year Number",
            "lineageTag": "8a9d683c-6e60-4f41-8359-48def0eb8ca0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year",
            "dataType": "string",
            "sourceColumn": "Calendar Year",
            "lineageTag": "0db24fa7-60f6-4fb0-bf6e-6375f760d70e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year Quarter Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calendar Year Quarter Number",
            "lineageTag": "7acd2e56-d399-4db4-b23b-331b72ec63a2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year Quarter",
            "dataType": "string",
            "sourceColumn": "Calendar Year Quarter",
            "lineageTag": "4de21cfb-f3d3-4a48-80f8-891d1aa24513",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year Month Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Calendar Year Month Number",
            "lineageTag": "f15e222b-ff82-42fc-a8fd-b0b495616648",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Calendar Year Month",
            "dataType": "string",
            "sourceColumn": "Calendar Year Month",
            "lineageTag": "925c04b7-3ede-4a21-9cb1-da9bc16c748e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Month Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Month Number",
            "lineageTag": "a31c78c7-c436-498f-a410-41aecd1c9a9c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "sourceColumn": "Month",
            "lineageTag": "dbe4953b-b9e8-47d8-ace9-fe6f73e29653",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Day of Week Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Day of Week Number",
            "lineageTag": "b7e2a798-5646-443c-9c9b-551708d36289",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Day of Week",
            "dataType": "string",
            "sourceColumn": "Day of Week",
            "lineageTag": "4db8448a-606d-48e6-8f99-7cdc1d4568d2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Year Number",
            "dataType": "int64",
            "sourceColumn": "Fiscal Year Number",
            "lineageTag": "1af53e2f-086b-46c1-baa7-e99f13deae66",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Year",
            "dataType": "string",
            "sourceColumn": "Fiscal Year",
            "lineageTag": "23811fc5-7517-4924-b227-6bc321263cfa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Quarter Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Quarter Number",
            "lineageTag": "b827a6f6-e665-4833-97b3-f8f2c777dd44",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Quarter",
            "dataType": "string",
            "sourceColumn": "Fiscal Quarter",
            "lineageTag": "92d121eb-b482-45b9-a1a3-aed752e5b6d7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Year Quarter Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Year Quarter Number",
            "lineageTag": "384b0308-6309-44ea-bfbf-d4676a5b1686",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Year Quarter",
            "dataType": "string",
            "sourceColumn": "Fiscal Year Quarter",
            "lineageTag": "86a9710e-a7f0-4d54-a690-a64429833a6a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Month Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Fiscal Month Number",
            "lineageTag": "957a9faa-a56f-417a-b63c-ce9216105863",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Fiscal Month",
            "dataType": "string",
            "sourceColumn": "Fiscal Month",
            "lineageTag": "1a0b0835-9097-475c-b8b4-86d7f4be6cbb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Working Day",
            "dataType": "string",
            "sourceColumn": "Working Day",
            "lineageTag": "99c9cc34-51e6-41a1-ae57-948bf2ae4698",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Is Holiday",
            "dataType": "int64",
            "sourceColumn": "Is Holiday",
            "lineageTag": "9f364bf1-9c17-4b43-bae9-439b9722fa8f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Holiday Name",
            "dataType": "string",
            "sourceColumn": "Holiday Name",
            "lineageTag": "c40a3887-9911-40ff-acb2-e787ef78b196",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Europe Season",
            "dataType": "string",
            "sourceColumn": "Europe Season",
            "lineageTag": "9a63049d-0d29-48d5-a901-c500f6046db0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "North America Season",
            "dataType": "string",
            "sourceColumn": "North America Season",
            "lineageTag": "b04afd93-68d0-45ed-9f4c-66ade9375f36",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Asia Season",
            "dataType": "string",
            "sourceColumn": "Asia Season",
            "lineageTag": "7559bec9-715e-4916-9caf-8f53e1ffdd60",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DaxBook Date",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\"),",
                "    DaxBook_Date = Source{[Schema=\"DaxBook\",Item=\"Date\"]}[Data]",
                "in",
                "    DaxBook_Date"
              ]
            },
            "annotations": [
              {
                "name": "IsQueryEditorUsed",
                "value": "False"
              },
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT * FROM [Date]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "290"
          },
          {
            "name": "IsQueryEditorUsed",
            "value": "False"
          },
          {
            "name": "QueryEditorSerialization"
          },
          {
            "name": "TableWidgetSerialization"
          },
          {
            "name": "DataMarketWebBaseUrl"
          },
          {
            "name": "DataMarketWebQueryUrl"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Product",
        "lineageTag": "626ec075-d883-44da-ac38-21d5bcc64023",
        "columns": [
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isNullable": false,
            "sourceColumn": "ProductKey",
            "lineageTag": "5eab9d53-d413-4b98-945a-baddadc9606c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Product Code",
            "dataType": "string",
            "sourceColumn": "Product Code",
            "lineageTag": "3e0ea871-e856-4dec-96dd-6d5cb83bf595",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name",
            "lineageTag": "c9efca7e-7e37-4eb9-ae11-5a813f081908",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Manufacturer",
            "dataType": "string",
            "sourceColumn": "Manufacturer",
            "lineageTag": "1af8dfe5-693c-41d8-9e54-7f80f5b5ba5f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "lineageTag": "81021e8a-76de-489a-91cf-747bfa825171",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "lineageTag": "3318ab39-e801-4812-b9fd-3ade8b9e139c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Weight",
            "dataType": "double",
            "sourceColumn": "Weight",
            "lineageTag": "b8d5fc48-4a66-411a-87af-7de6f69ce64b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Weight Unit Measure",
            "dataType": "string",
            "sourceColumn": "Weight Unit Measure",
            "lineageTag": "8a5337e8-5eab-4d58-898c-ce47ce51eef3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost",
            "lineageTag": "c9d1ad24-12e9-4128-a8bf-d753bdf1a56e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price",
            "lineageTag": "1a18f56d-014d-4093-a13d-77dc9eb3c53b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Available Date",
            "dataType": "dateTime",
            "sourceColumn": "Available Date",
            "formatString": "General Date",
            "lineageTag": "95d722f8-2135-4bd7-abad-e5e83b3ec7ec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Subcategory",
            "dataType": "string",
            "sourceColumn": "Subcategory",
            "lineageTag": "ce79a53c-c2e8-452e-bc28-2e2d37080df6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Category",
            "dataType": "string",
            "sourceColumn": "Category",
            "lineageTag": "807971a5-f3e6-45b4-8ac6-d2d0a5512f70",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DaxBook Product",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\"),",
                "    DaxBook_Product = Source{[Schema=\"DaxBook\",Item=\"Product\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(DaxBook_Product,{\"Class\", \"Style\", \"Size\", \"Stock Type Code\", \"Stock Type\", \"Status\", \"Product Description\"}),",
                "    #\"Merged Queries\" = Table.NestedJoin(#\"Removed Columns\",{\"ProductSubcategoryKey\"},#\"Product Subcategory\",{\"ProductSubcategoryKey\"},\"Product Subcategory\",JoinKind.LeftOuter),",
                "    #\"Expanded Product Subcategory\" = Table.ExpandTableColumn(#\"Merged Queries\", \"Product Subcategory\", {\"Subcategory\", \"ProductCategoryKey\"}, {\"Subcategory\", \"ProductCategoryKey\"}),",
                "    #\"Removed Columns1\" = Table.RemoveColumns(#\"Expanded Product Subcategory\",{\"ProductSubcategoryKey\"}),",
                "    #\"Merged Queries1\" = Table.NestedJoin(#\"Removed Columns1\",{\"ProductCategoryKey\"},#\"Product Category\",{\"ProductCategoryKey\"},\"Product Category\",JoinKind.LeftOuter),",
                "    #\"Expanded Product Category\" = Table.ExpandTableColumn(#\"Merged Queries1\", \"Product Category\", {\"Category\"}, {\"Category\"}),",
                "    #\"Removed Columns2\" = Table.RemoveColumns(#\"Expanded Product Category\",{\"ProductCategoryKey\"})",
                "in",
                "    #\"Removed Columns2\""
              ]
            },
            "annotations": [
              {
                "name": "IsQueryEditorUsed",
                "value": "False"
              },
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "hierarchies": [
          {
            "name": "Manufacturer Hierarchy",
            "lineageTag": "c5c2ce7a-cb14-41d8-8572-cb6caa7c2df4",
            "levels": [
              {
                "name": "Manufacturer",
                "ordinal": 0,
                "column": "Manufacturer",
                "lineageTag": "d445eba9-31a4-4b68-b73e-8ffc4e554a20"
              },
              {
                "name": "Color",
                "ordinal": 1,
                "column": "Color",
                "lineageTag": "d3cf31eb-7d32-4e57-8fe5-de3e40b7cc20"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT * FROM [Product]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "525"
          },
          {
            "name": "IsQueryEditorUsed",
            "value": "False"
          },
          {
            "name": "QueryEditorSerialization"
          },
          {
            "name": "TableWidgetSerialization"
          },
          {
            "name": "DataMarketWebBaseUrl"
          },
          {
            "name": "DataMarketWebQueryUrl"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Promotion",
        "lineageTag": "dfccd2dd-0916-44c0-934c-3679c68cefe0",
        "columns": [
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "PromotionKey",
            "lineageTag": "22f2faf8-6611-4f38-81f2-71dc28d21eb8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Promotion Code",
            "dataType": "string",
            "sourceColumn": "Promotion Code",
            "lineageTag": "93dd54dd-a1d8-49ed-97ad-4c1c49333472",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Promotion",
            "dataType": "string",
            "sourceColumn": "Promotion",
            "lineageTag": "55b301e6-71dd-41c6-9fb4-b0a0fa111c66",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Discount",
            "dataType": "double",
            "sourceColumn": "Discount",
            "lineageTag": "bc63a1aa-728e-4853-875f-d6efbfbc039f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Promotion Type",
            "dataType": "string",
            "sourceColumn": "Promotion Type",
            "lineageTag": "8b67e063-a0bb-43a4-8498-493f3010c086",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Promotion Category",
            "dataType": "string",
            "sourceColumn": "Promotion Category",
            "lineageTag": "bce4c5cf-f83a-4cd7-8e76-d1cce03041c7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Start Date",
            "dataType": "dateTime",
            "sourceColumn": "Start Date",
            "formatString": "General Date",
            "lineageTag": "f63200c4-8ba7-43ae-9b9a-b2741be46cfb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "End Date",
            "dataType": "dateTime",
            "sourceColumn": "End Date",
            "formatString": "General Date",
            "lineageTag": "419ff928-8b98-4e60-a5be-67ef3b65f3c4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DaxBook Promotion",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\"),",
                "    DaxBook_Promotion = Source{[Schema=\"DaxBook\",Item=\"Promotion\"]}[Data]",
                "in",
                "    DaxBook_Promotion"
              ]
            },
            "annotations": [
              {
                "name": "IsQueryEditorUsed",
                "value": "False"
              },
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT * FROM [Promotion]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "814"
          },
          {
            "name": "IsQueryEditorUsed",
            "value": "False"
          },
          {
            "name": "QueryEditorSerialization"
          },
          {
            "name": "TableWidgetSerialization"
          },
          {
            "name": "DataMarketWebBaseUrl"
          },
          {
            "name": "DataMarketWebQueryUrl"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Sales",
        "lineageTag": "3320075e-9de1-4895-a345-5c4c7f2bd1d9",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "StoreKey",
            "lineageTag": "82018dac-7a23-40b6-ba05-37a81c8d323f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "ProductKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "ProductKey",
            "lineageTag": "0d6a5a23-fb4f-431a-a57f-0dfe165fe659",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "PromotionKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "PromotionKey",
            "lineageTag": "54d15f37-c238-4d3d-817f-d0d1bc66a46a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "CurrencyKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CurrencyKey",
            "lineageTag": "35bfa262-45d6-407f-a68c-a1d9e96aa17e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "CustomerKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "CustomerKey",
            "lineageTag": "fe29188e-e78f-424d-a8aa-f196382c3d4b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "OrderDateKey",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "OrderDateKey",
            "lineageTag": "2e25f7dd-9134-4151-af89-4d749fb4f2f6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "sourceColumn": "Order Date",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "4832cf64-bfdb-491f-8a5f-f08d060fe1fd",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "Delivery Date",
            "dataType": "dateTime",
            "sourceColumn": "Delivery Date",
            "formatString": "mm/dd/yyyy",
            "lineageTag": "0e95eb6a-2718-4889-88d4-95eb4b896e0e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isDateTimeCustom\":true}"
              }
            ]
          },
          {
            "name": "Order Number",
            "dataType": "string",
            "sourceColumn": "Order Number",
            "lineageTag": "4f1fd095-7a93-4d63-b752-b327d8d3659d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Order Line Number",
            "dataType": "int64",
            "sourceColumn": "Order Line Number",
            "lineageTag": "68e6b657-68c4-4401-8347-735c98fdc5a5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Quantity",
            "dataType": "int64",
            "sourceColumn": "Quantity",
            "formatString": "#,0",
            "lineageTag": "a02ace52-de84-4f44-80a7-f5b00005da54",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Unit Price",
            "dataType": "decimal",
            "sourceColumn": "Unit Price",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "5ef003b3-b3ae-4803-b2f9-6e4b2a9268c2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Unit Discount",
            "dataType": "decimal",
            "sourceColumn": "Unit Discount",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "8afb2da5-3f23-44ea-9879-884dddc04881",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Unit Cost",
            "dataType": "decimal",
            "sourceColumn": "Unit Cost",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "b23b9f2e-89e8-4530-bb2a-8887a7967001",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Net Price",
            "dataType": "decimal",
            "sourceColumn": "Net Price",
            "formatString": "\\$#,0.00;(\\$#,0.00);\\$#,0.00",
            "lineageTag": "58f4169b-ee52-4fa1-b35d-305ea4d69f0b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DaxBook Sales",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\"),",
                "    DaxBook_Sales = Source{[Schema=\"DaxBook\",Item=\"Sales\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(DaxBook_Sales,{\"OnlineSalesKey\", \"Due Date\", \"DueDateKey\", \"DeliveryDateKey\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            },
            "annotations": [
              {
                "name": "IsQueryEditorUsed",
                "value": "False"
              },
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "measures": [
          {
            "name": "Sales Amount",
            "expression": "SUMX ( Sales, Sales[Quantity] * Sales[Net Price] )",
            "formatString": "#,0.00",
            "lineageTag": "247bd9a8-6303-4e25-b60b-582cd01dbff6"
          },
          {
            "name": "Sales Pct All Products and Customers",
            "expression": [
              "",
              "VAR CurrentCategorySales = ",
              "    [Sales Amount]",
              "VAR AllProductAndCustomersSales = ",
              "    CALCULATE( ",
              "        [Sales Amount], ",
              "        ALL ( 'Product' ),",
              "        ALL ( Customer )",
              "    )",
              "VAR Ratio =",
              "    DIVIDE ( ",
              "        CurrentCategorySales, ",
              "        AllProductAndCustomersSales",
              "    )",
              "RETURN Ratio"
            ],
            "formatString": "0.00%;-0.00%;0.00%",
            "lineageTag": "5a3780d3-7fb8-420b-b2ac-143583ada9bf"
          },
          {
            "name": "All Category Sales",
            "expression": "CALCULATE( [Sales Amount], ALL ( 'Product'[Category] ) )",
            "formatString": "#,0.00",
            "lineageTag": "da888c98-179c-4ef1-a232-8ea936b8829d"
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT * FROM [Sales]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "905"
          },
          {
            "name": "IsQueryEditorUsed",
            "value": "False"
          },
          {
            "name": "QueryEditorSerialization"
          },
          {
            "name": "TableWidgetSerialization"
          },
          {
            "name": "DataMarketWebBaseUrl"
          },
          {
            "name": "DataMarketWebQueryUrl"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Store",
        "lineageTag": "ab934937-61ff-4d80-ba67-50c3c15e6116",
        "columns": [
          {
            "name": "StoreKey",
            "dataType": "int64",
            "isHidden": true,
            "isNullable": false,
            "sourceColumn": "StoreKey",
            "lineageTag": "8b0fa405-8592-42cd-b45d-c7d391a986d5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Store Type",
            "dataType": "string",
            "sourceColumn": "Store Type",
            "lineageTag": "90a79ad9-b077-4cd3-9b90-2275a2df210c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Store Name",
            "dataType": "string",
            "sourceColumn": "Store Name",
            "lineageTag": "148fea69-bede-47f3-9070-0d6a476a27c4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Status",
            "dataType": "string",
            "sourceColumn": "Status",
            "lineageTag": "6e87976c-7b62-4f8e-900c-b446eeecc711",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Open Date",
            "dataType": "dateTime",
            "sourceColumn": "Open Date",
            "formatString": "General Date",
            "lineageTag": "f252467a-0d84-47a7-ba13-7a4e1b2ece2f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Close Date",
            "dataType": "dateTime",
            "sourceColumn": "Close Date",
            "formatString": "General Date",
            "lineageTag": "90c286f4-33b7-4d4f-b308-97b6932c1d70",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Zip Code",
            "dataType": "string",
            "sourceColumn": "Zip Code",
            "lineageTag": "383f35db-d40b-498d-981e-a61199a145aa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Zip Code Extension",
            "dataType": "string",
            "sourceColumn": "Zip Code Extension",
            "lineageTag": "dddec207-5489-4528-8007-2875b683286d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Store Phone",
            "dataType": "string",
            "sourceColumn": "Store Phone",
            "lineageTag": "73cf2648-b5aa-49d8-af27-48ab896f848a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Continent",
            "dataType": "string",
            "sourceColumn": "Continent",
            "lineageTag": "dec82311-1494-4ba5-ad07-7980cfa976ab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "City",
            "dataType": "string",
            "sourceColumn": "City",
            "lineageTag": "0aabede6-9d61-446b-a571-cf78c83ad75f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "State",
            "dataType": "string",
            "sourceColumn": "State",
            "lineageTag": "e8a3ed6b-4e58-45ac-8fd0-839d0b6c0773",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Address Line 1",
            "dataType": "string",
            "sourceColumn": "Address Line 1",
            "lineageTag": "73e7172f-dc35-4c3e-95ba-bca9bfdc71e7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Address Line 2",
            "dataType": "string",
            "sourceColumn": "Address Line 2",
            "lineageTag": "e6decf34-01d2-4b0f-9acf-a1c50613d1f4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Close Reason",
            "dataType": "string",
            "sourceColumn": "Close Reason",
            "lineageTag": "10ad55dc-8efb-46a5-b08b-ee08c474f5bb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          },
          {
            "name": "Employees",
            "dataType": "int64",
            "sourceColumn": "Employees",
            "lineageTag": "470efb5a-a6fa-40aa-a928-25820d5a9945",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Selling Area",
            "dataType": "double",
            "sourceColumn": "Selling Area",
            "lineageTag": "06f2c271-3e09-409b-ab2e-ff9d93fce2f1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Last Remodel Date",
            "dataType": "dateTime",
            "sourceColumn": "Last Remodel Date",
            "formatString": "General Date",
            "lineageTag": "6e3d5d5d-e8cf-40dd-9b11-2ac59e096cc5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "CountryRegion",
            "dataType": "string",
            "sourceColumn": "CountryRegion",
            "lineageTag": "fffac954-e125-4b26-948b-152e6403fe09",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isText\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DaxBook Store",
            "mode": "import",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\"),",
                "    DaxBook_Store = Source{[Schema=\"DaxBook\",Item=\"Store\"]}[Data],",
                "    #\"Removed Columns\" = Table.RemoveColumns(DaxBook_Store,{\"GeographyKey\", \"Store Manager\", \"StoreFax\"})",
                "in",
                "    #\"Removed Columns\""
              ]
            },
            "annotations": [
              {
                "name": "IsQueryEditorUsed",
                "value": "False"
              },
              {
                "name": "QueryEditorSerialization"
              },
              {
                "name": "TableWidgetSerialization"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "_TM_ExtProp_QueryDefinition",
            "value": "SELECT * FROM [Store]"
          },
          {
            "name": "_TM_ExtProp_DbTableName",
            "value": "1084"
          },
          {
            "name": "IsQueryEditorUsed",
            "value": "False"
          },
          {
            "name": "QueryEditorSerialization"
          },
          {
            "name": "TableWidgetSerialization"
          },
          {
            "name": "DataMarketWebBaseUrl"
          },
          {
            "name": "DataMarketWebQueryUrl"
          },
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "ab1aeb10-6713-4f0f-9473-659c672a8d57",
        "fromTable": "Sales",
        "fromColumn": "ProductKey",
        "toTable": "Product",
        "toColumn": "ProductKey"
      },
      {
        "name": "a6597a69-f336-46f0-92c1-1b4e4b5da1be",
        "fromTable": "Sales",
        "fromColumn": "CustomerKey",
        "toTable": "Customer",
        "toColumn": "CustomerKey"
      },
      {
        "name": "82e366d6-93db-4102-98c1-a3c1d1bcd8bb",
        "fromTable": "Sales",
        "fromColumn": "PromotionKey",
        "toTable": "Promotion",
        "toColumn": "PromotionKey"
      },
      {
        "name": "9b15e4cb-1b76-41fe-a25b-a71823fb4ad1",
        "fromTable": "Sales",
        "fromColumn": "StoreKey",
        "toTable": "Store",
        "toColumn": "StoreKey"
      },
      {
        "name": "9ce5317f-f1ca-4fe2-b8ee-783b3b45e387",
        "fromTable": "Sales",
        "fromColumn": "OrderDateKey",
        "toTable": "Date",
        "toColumn": "DateKey"
      },
      {
        "name": "4a642774-4900-4016-8a73-a9f13e30a6b6",
        "fromTable": "Sales",
        "fromColumn": "Delivery Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {
          "content": {
            "Version": "1.0.0",
            "Language": "en-US"
          },
          "contentType": "json"
        }
      }
    ],
    "expressions": [
      {
        "name": "Product Category",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\"),",
          "    #\"DaxBook_Product Category\" = Source{[Schema=\"DaxBook\",Item=\"Product Category\"]}[Data]",
          "in",
          "    #\"DaxBook_Product Category\""
        ],
        "lineageTag": "3c33e234-a808-4bd8-b784-3c88f702312f",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Product Subcategory",
        "kind": "m",
        "expression": [
          "let",
          "    Source = Sql.Database(\"Demo\", \"ContosoRetailDW\"),",
          "    #\"DaxBook_Product Subcategory\" = Source{[Schema=\"DaxBook\",Item=\"Product Subcategory\"]}[Data]",
          "in",
          "    #\"DaxBook_Product Subcategory\""
        ],
        "lineageTag": "db127515-ce4b-4109-b07c-348a3cc26c14",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      }
    ],
    "annotations": [
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.140.1577.0 (25.02)+00af0910c5ca19a229c472b0dfc17a2c488f6b0a"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Customer\",\"Date\",\"Product\",\"Product Category\",\"Product Subcategory\",\"Promotion\",\"Sales\",\"Store\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Shared Expressions\",\"Perspectives\",\"Relationships\",\"Roles\",\"Tables\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Tables/Calculation Items\",\"Translations\"]}"
      }
    ]
  }
}